app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('contact.urls')),
    path('authentication/', include('authentication.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path

from contact import views

app_name = 'contact'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search_contacts, name='search'),
    path('contact/<int:contact_id>', views.contact, name='contact'),
    path('contact/create/', views.create, name='create'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),
]

contact/models.py
"""
 Contact models
"""
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import  User

class Category(models.Model):
    """
    Category model
    """
    name = models.CharField(max_length=254)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        """Category model metadata"""
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self) -> str:
        return f'{self.name}'


class Contact(models.Model):
    """ 
    Contact model
    """
    name = models.CharField(max_length=254)
    email = models.EmailField(max_length=254)
    phone_number = models.CharField(max_length=20)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    is_visible = models.BooleanField(default=True)
    picture = models.ImageField(
        blank=True, null=True, upload_to='pictures/contacts/%Y/%m/')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True)
    owner = models.ForeignKey(User,on_delete=models.SET_NULL,blank=True,null=True)

    def __str__(self):
        return f'{self.name} / {self.email} / {self.phone_number}'

contact/forms/create_contact.py
from django import forms
from django.core.exceptions import ValidationError

from contact.models import Contact


class ContactForm(forms.ModelForm):
    """ Contact Form """

    picture = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'accept': 'image/*',
            }
        ),
        required=False
    )

    name = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'Type your name here'
        }),
        help_text='Type the contact name here'
    )

    class Meta:
        """ Contact Form Meta """
        model = Contact
        fields = (
            'name', 'phone_number',
            'email', 'description', 'category',
            'picture',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean_name(self):
        """ Name must have at least 3 characters """
        name = self.cleaned_data.get('name', '')
        if len(name) < 3:
            self.add_error(
                'name',
                ValidationError(
                    'Name must have at least 3 characters',
                    code='invalid'
                )
            )
        return name

    def clean_phone_number(self):
        """ Phone number must have at least 11 digits """
        phone_number = self.cleaned_data.get('phone_number', '')
        if len(phone_number) < 11:
            self.add_error(
                'phone_number',
                ValidationError(
                    'Phone number must have at least 11 digits',
                    code='invalid'
                )
            )
        return phone_number

contact/views.py
""" Contacts Views """
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

# Create your views here.


def index(request: HttpRequest) -> HttpResponse:
    """_summary_
    Contact index view
    Args:
        request (HttpRequest): _description_

    Returns:
        HttpResponse: _description_
    """
    return render(request, 'contact/pages/index.html')

contact/views/contact_forms.py
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from contact.forms import ContactForm
from contact.models import Contact


@login_required(login_url="authentication:signin")
def create(request: HttpRequest) -> HttpResponse:
    """_summary_
        Create Contact view
    """
    form_action = reverse('contact:create')
    form = ContactForm(data=request.POST,
                       files=request.FILES)
    if not request.method == "GET":
        context = {
            "document_title": 'New Contact',
            'form': form,
            "form_action": form_action
        }
        if form.is_valid():
            created_contact = form.save(commit=False)
            created_contact.owner = request.user
            created_contact.save()
            contact_id = created_contact.pk
            return redirect('contact:update', contact_id=contact_id)

        return render(request, 'contact/pages/create.html', context)

    new_form = ContactForm()
    context = {
        "document_title": 'New Contact',
        'form': new_form,
        "form_action": form_action
    }
    return render(request, 'contact/pages/create.html', context)


@login_required(login_url="authentication:signin")
def update(request: HttpRequest, contact_id) -> HttpResponse:
    """_summary_
        Update Contact view
    """
    user = request.user
    contact = get_object_or_404(
        Contact, pk=contact_id, is_visible=True, owner=user.pk)

    form_action = reverse('contact:update', args=(contact_id,))
    form = ContactForm(data=request.POST,
                       files=request.FILES, instance=contact)

    if not request.method == "GET":
        context = {
            "document_title": 'Update Contact',
            'form': form,
            "form_action": form_action
        }
        if form.is_valid():
            created_contact = form.save()
            contact_id = created_contact.pk
            print(f'{created_contact}')
            return redirect('contact:update', contact_id=contact_id)
        return render(request, 'contact/pages/create.html', context)

    new_form = ContactForm(instance=contact)

    context = {
        "document_title": 'Update Contact',
        'form': new_form,
        "form_action": form_action
    }
    return render(request, 'contact/pages/create.html', context)


@login_required(login_url="authentication:signin")
def delete(request: HttpRequest, contact_id) -> HttpResponse:
    """_summary_
        Delete Contact view
    """
    user = request.user
    contact = get_object_or_404(
        Contact, pk=contact_id, is_visible=True, owner=user.pk)
    confirmation = request.POST.get('confirmation', 'no')

    context = {
        "document_title": 'Delete Contact',
        'contact': contact,
        "confirmation": confirmation
    }

    if confirmation == 'yes':
        contact.delete()
        return redirect('contact:index')
    return render(request, 'contact/pages/contact.html', context=context)

contact/views/contact_views.py
""" Contacts Views """
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from contact.models import Contact


@login_required(login_url="authentication:signin")
def index(request: HttpRequest) -> HttpResponse:
    """_summary_
        Contact index view
    """
    user = request.user
    contacts = Contact.objects.filter(
        is_visible=True, owner=user.pk).order_by("-id")

    paginator = Paginator(contacts, 12)

    page_number = request.GET.get("page", 1)
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'contact/pages/index.html', context)


@login_required(login_url="authentication:signin")
def search_contacts(request: HttpRequest) -> HttpResponse:
    """_summary_
        Contact index view
    """
    search_term = request.GET.get('q', '').strip()

    if not search_term:
        return redirect('contact:index')
    user = request.user

    contacts = Contact.objects.filter(
        Q(name__icontains=search_term) | Q(email__icontains=search_term),
        is_visible=True, owner=user.pk
    ).order_by("-id")

    paginator = Paginator(contacts, 12)

    page_number = request.GET.get("page", 1)
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj
    }
    return render(request, 'contact/pages/index.html', context)


@login_required(login_url="authentication:signin")
def contact(request: HttpRequest, contact_id: int) -> HttpResponse:
    """_summary_
        Contact view
    """
    target_contact = get_object_or_404(Contact, pk=contact_id, is_visible=True)

    context = {
        "document_title": f'{target_contact.name}',
        'contact': target_contact
    }
    return render(request, 'contact/pages/contact.html', context)

contact/templates/contact/pages/contact.html
{% extends "global/base.html" %} {% block content %}
<div class="single-contact">
  <h1 class="single-contact-name">{{contact.name}}</h1>
  <p>
    <b> ID: </b>
    {{contact.id}}
  </p>

  <p>
    <b> Name: </b>
    {{contact.name}}
  </p>

  <p>
    <b> PHONE: </b>
    {{contact.phone_number}}
  </p>

  <p>
    <b> EMAIL: </b>
    {{contact.email}}
  </p>
  <p>
    <b> Description: </b>
    {{contact.description}}
  </p>

  <p>
    <b> Category: </b>
    {{contact.category.name}}
  </p>

  <p>
    <b> Created at: </b>
    {{contact.created_at}}
  </p>
  {% if contact.picture %}
  <p><img src="{{contact.picture.url}}" alt="{{contact.name}}"></p>
  {% endif %}
</div>


<div class="contact-links">
  <a class="btn btn-link" href="{% url 'contact:update' contact.id %}">Update</a>

  <form action="{% url 'contact:delete' contact.id %}" method="POST">
    {% csrf_token %}

    {% if confirmation == 'no' %}
      <input type="hidden" name="confirmation" value="yes">
      <button class="btn btn-link btn-delete" type="submit">Confirma?</button>
    {% else %}
      <button class="btn btn-link btn-delete" type="submit">Delete</button>
    {% endif %}
  </form>
</div>
{% endblock content %}

contact/templates/contact/pages/create.html
{% extends "global/base.html" %} {% block content %}
<div class="form-wrapper">
  <h2>Contact</h2>

  <form action="{{form_action}}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-content">
      {% for field in form %}
      
      <div class="form-group">
        <label for="{{field.id_for_label}}">{{field.label}}</label>
        {{field}} 
        {{field.errors}}

        {% if field.help_text %}
        <p class="help-text">
          {{field.help_text}}
        </p>
        {% endif %}


      </div>
         {% if field.name == 'picture' and field.value.url %}
            <div class="form-group">
              <img src="{{ field.value.url }}" alt="">
            </div>
          {% endif %}
      {% endfor %}

      
      {% if form.non_field_errors %}
      <div class="form-content">
        <div class="form-group">
          <div class="message error">{{form.non_field_errors}}</div>
        </div>
      </div>
      {% endif %}

    </div>

    <div class="form-content">
      <div class="form-group">
        <button class="btn" type="submit">Send</button>
      </div>
    </div>
  </form>
</div>

{% endblock content %}

contact/templates/contact/pages/index.html
{% extends "global/base.html" %} {% block content %}

{% if page_obj %}

<div class="repsonsive-table">
  <table class="contacts-table">
    <caption class="table-caption">
      Contacts
    </caption>
    <thead>
      <tr class="table-row table-row-header">
        <th class="table-header">ID</th>
        <th class="table-header">name</th>
        <th class="table-header">phone</th>
        <th class="table-header">email</th>
      </tr>
    </thead>
    <tbody>
      {% for contact in page_obj %}
      <tr class="table-row">
        <td class="table-cel">
          <a href="{% url 'contact:contact' contact.id %}">
            {{ contact.id }}
          </a>
        </td>
        <td class="table-cel">{{ contact.name }}</td>
        <td class="table-cel">{{ contact.phone_number }}</td>
        <td class="table-cel">{{ contact.email }}</td>
      </tr>
       {% endfor %}
      </tr>
    </tbody>
  </table>
</div>

{% else %}
<div class="single-contact">
  <h1 class="single-contact-name">Nothing found :(</h1>
</div>
{% endif %}


{% endblock content %}